version: '3'

services:
  mongodb:
    image: mongo:3.6.13-xenial
    command: --smallfiles
    volumes:
      - mongodbvolume:/data/db
    ports:
      - '27018:27017'
    networks:
      - note-service

  note-service:
    env_file: .envrc.sample
    build:
      context: '.'
    restart: always
    depends_on:
      - mongodb
    ports:
      - '50051:50051'
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/app/logs'
    networks:
      - note-service
    links:
      - mongodb

networks:
  note-service:
    driver: bridge

volumes:
  mongodbvolume:
